name: deploy
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      # see https://zellwk.com/blog/github-actions-deploy/
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_DEPLOY_KEY }} 
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOSTNAME }} >> ~/.ssh/known_hosts
      - name: test1
        run: ls -al /home/runner/.ssh
      - name: test2
        run: head /home/runner/.ssh/id_rsa
      - name: test4
        run: ssh contabo.matb.it date
      - name: deploy
        run: ssh ${{ secrets.SSH_HOSTNAME }} dungeon/DEPLOY.sh